import { imagePaths } from "@/lib/image-paths";

export type PropertyRoom = {
  name: string;
  image: string;
};

export type Property = {
  id: string;
  name: string;
  slug: string;
  location: string;
  area: string;
  propertyType: string;
  collection?: "City stays" | "Homes" | "Signature stays";
  guests: string;
  maxGuests: number;
  price: string;
  priceValue: number;
  currency: "MYR";
  heroImage: string;
  imageAlt: string;
  galleryImages: string[];
  galleryCaptions: string[];
  shortDescription: string;
  description: string;
  bedrooms: string;
  beds: string;
  bathrooms: string;
  amenities: string[];
  houseRules: string[];
  rooms: PropertyRoom[];
  status?: "DRAFT" | "PUBLISHED" | "ARCHIVED";
};

export type BookingStatus =
  | "PENDING"
  | "REQUESTED"
  | "REVIEWING"
  | "CONFIRMED"
  | "REJECTED"
  | "DECLINED"
  | "CANCELLED";

export const contactDetails = {
  email: "hello@homestaybypatricia.com",
  location: "Setia Alam, Selangor, Malaysia",
} as const;

const terraceImages = imagePaths.properties.property01;

const terraceGallery = [
  terraceImages.loungeWide,
  terraceImages.exteriorGarden,
  terraceImages.openLivingDining,
  terraceImages.diningTable,
  terraceImages.mainKitchen,
  terraceImages.queenBedroom,
  terraceImages.twinBedroom,
  terraceImages.bunkRoom,
  terraceImages.singleBedroom,
  terraceImages.balcony,
  terraceImages.tvLounge,
  terraceImages.bathroom,
  terraceImages.staircase,
  terraceImages.diningCorner,
  terraceImages.kitchenette,
  terraceImages.exteriorFacade,
  terraceImages.livingVertical,
  terraceImages.stairLounge,
  terraceImages.balconyBedroom,
];

const terraceCaptions = [
  "Open lounge",
  "Garden exterior",
  "Living and dining",
  "Dining table",
  "Kitchen",
  "Queen bedroom",
  "Twin bedroom",
  "Bunk room",
  "Single bedroom",
  "Balcony",
  "TV lounge",
  "Bathroom",
  "Staircase",
  "Dining corner",
  "Kitchenette",
  "Exterior facade",
  "Living room detail",
  "Stair lounge",
  "Balcony bedroom",
];

const baseProperties: Property[] = [
  {
    id: "property-001",
    name: "Patricia Modern Terrace Homestay",
    slug: "patricia-modern-terrace-homestay",
    location: "Setia Alam, Selangor",
    area: "Setia Alam",
    propertyType: "Private terrace home",
    guests: "Up to 8 guests",
    maxGuests: 8,
    price: "From RM 620 / night",
    priceValue: 620,
    currency: "MYR",
    heroImage: terraceImages.loungeWide,
    imageAlt: "Open living lounge with dining area at Patricia Modern Terrace Homestay",
    galleryImages: terraceGallery,
    galleryCaptions: terraceCaptions,
    shortDescription:
      "A polished private terrace home with warm living spaces, multiple bedrooms, a balcony, and a quiet residential feel.",
    description:
      "This modern terrace homestay is arranged for families and small groups who want a comfortable private base in Selangor. The photographs show generous living and dining areas, a kitchen, several bedrooms, a balcony, and a bathroom, with a calm residential setting outside.",
    bedrooms: "4 bedrooms",
    beds: "5 beds",
    bathrooms: "2 bathrooms",
    amenities: [
      "Air conditioning",
      "Wi-Fi",
      "Kitchen",
      "Dining area",
      "Balcony",
      "Private bedrooms",
      "Family living area",
    ],
    houseRules: [
      "Respect the home and surrounding neighbours.",
      "No parties or events.",
      "Smoking is not permitted indoors.",
      "Booking requests are only confirmed after Patricia approves them.",
    ],
    rooms: [
      { name: "Queen bedroom", image: terraceImages.queenBedroom },
      { name: "Twin bedroom", image: terraceImages.twinBedroom },
      { name: "Bunk room", image: terraceImages.bunkRoom },
      { name: "Single bedroom", image: terraceImages.singleBedroom },
    ],
  },
];

function propertyPhoto(folder: string, filename: string) {
  return `/images/properties/${folder}/${filename}`;
}

function propertyPhotos(folder: string, filenames: string[], captions: string[]) {
  return {
    galleryImages: filenames.map((filename) => propertyPhoto(folder, filename)),
    galleryCaptions: captions,
  };
}

const standardAmenities = ["Air conditioning", "Wi-Fi", "Kitchen", "Private bathroom", "Living area"];
const standardRules = ["Respect the home and surrounding neighbours.", "No parties or events.", "Smoking is not permitted indoors.", "Booking requests are confirmed after review."];

const galleryProperties: Property[] = [
  {
    id: "property-005",
    name: "Skyline Balcony Residence",
    slug: "skyline-balcony-residence",
    location: "Kuala Lumpur, Malaysia",
    area: "KLCC",
    propertyType: "Entire apartment",
    collection: "City stays",
    guests: "Up to 4 guests",
    maxGuests: 4,
    price: "From RM 490 / night",
    priceValue: 490,
    currency: "MYR",
    heroImage: propertyPhoto("property-05", "WhatsApp Image 2026-09-17 at 11.04.27 (2).jpeg"),
    imageAlt: "Balcony view from the Skyline Balcony Residence",
    ...propertyPhotos("property-05", ["WhatsApp Image 2026-09-17 at 11.04.27 (1).jpeg", "WhatsApp Image 2026-09-17 at 11.04.27 (2).jpeg", "WhatsApp Image 2026-09-17 at 11.04.27 (3).jpeg", "WhatsApp Image 2026-09-17 at 11.04.27 (4).jpeg", "WhatsApp Image 2026-09-17 at 11.04.27.jpeg", "WhatsApp Image 2026-09-17 at 11.04.28 (1).jpeg", "WhatsApp Image 2026-09-17 at 11.04.28.jpeg"], ["Walk-in shower", "Balcony view", "Living room", "Open kitchen", "Bedroom", "Dining nook", "City-facing lounge"]),
    shortDescription: "A polished apartment with a balcony, city outlook, and an easy open-plan living space.",
    description: "Designed for a relaxed city break, this apartment brings together a quiet bedroom, well-equipped kitchen, bright lounge, and a balcony looking across the skyline.",
    bedrooms: "2 bedrooms",
    beds: "2 beds",
    bathrooms: "1 bathroom",
    amenities: standardAmenities,
    houseRules: standardRules,
    rooms: [{ name: "Living room", image: propertyPhoto("property-05", "WhatsApp Image 2026-09-17 at 11.04.27 (3).jpeg") }, { name: "Bedroom", image: propertyPhoto("property-05", "WhatsApp Image 2026-09-17 at 11.04.28.jpeg") }],
  },
  {
    id: "property-006",
    name: "The Everyday City Apartment",
    slug: "everyday-city-apartment",
    location: "Kuala Lumpur, Malaysia",
    area: "Bukit Bintang",
    propertyType: "Entire apartment",
    collection: "City stays",
    guests: "Up to 3 guests",
    maxGuests: 3,
    price: "From RM 280 / night",
    priceValue: 280,
    currency: "MYR",
    heroImage: propertyPhoto("property-06", "1.jpeg"),
    imageAlt: "Dining room in The Everyday City Apartment",
    ...propertyPhotos("property-06", ["1.jpeg", "3.jpeg", "4.jpeg", "5.jpeg", "WhatsApp Image 2026-09-17 at 11.06.53.jpeg"], ["Dining room", "Kitchen", "Bedroom", "Bathroom", "Living space"]),
    shortDescription: "A clean, convenient apartment with a dining table, compact kitchen, and calm bedroom.",
    description: "A practical base with the essentials set out clearly: a place to cook, eat, rest, and reset between plans in the city.",
    bedrooms: "1 bedroom",
    beds: "2 beds",
    bathrooms: "1 bathroom",
    amenities: standardAmenities,
    houseRules: standardRules,
    rooms: [{ name: "Dining room", image: propertyPhoto("property-06", "1.jpeg") }, { name: "Bedroom", image: propertyPhoto("property-06", "4.jpeg") }],
  },
  {
    id: "property-007",
    name: "Midnight Modern Home",
    slug: "midnight-modern-home",
    location: "Malaysia",
    area: "Petaling Jaya",
    propertyType: "Entire home",
    collection: "Homes",
    guests: "Up to 6 guests",
    maxGuests: 6,
    price: "From RM 530 / night",
    priceValue: 530,
    currency: "MYR",
    heroImage: propertyPhoto("property-07", "H4.jpeg"),
    imageAlt: "Modern bedroom in the Midnight Modern Home",
    ...propertyPhotos("property-07", ["H1.jpeg", "H2.jpeg", "H3.jpeg", "H4.jpeg", "H5.jpeg", "H6.jpeg", "H7.jpeg"], ["Kitchen", "Primary bedroom", "Twin room", "Second bedroom", "Bathroom", "Lounge", "Dining area"]),
    shortDescription: "A dark-toned modern home with handsome bedrooms, a generous kitchen, and considered lighting.",
    description: "This home balances crisp modern finishes with bedrooms that feel settled and private, making it a natural fit for family or group stays.",
    bedrooms: "3 bedrooms",
    beds: "4 beds",
    bathrooms: "2 bathrooms",
    amenities: [...standardAmenities, "Dining area"],
    houseRules: standardRules,
    rooms: [{ name: "Primary bedroom", image: propertyPhoto("property-07", "H2.jpeg") }, { name: "Twin room", image: propertyPhoto("property-07", "H3.jpeg") }],
  },
  {
    id: "property-008",
    name: "Warmwood Studio",
    slug: "warmwood-studio",
    location: "Malaysia",
    area: "Cheras",
    propertyType: "Entire studio",
    collection: "City stays",
    guests: "Up to 2 guests",
    maxGuests: 2,
    price: "From RM 220 / night",
    priceValue: 220,
    currency: "MYR",
    heroImage: propertyPhoto("property-08", "WhatsApp Image 2026-09-17 at 11.06.50.jpeg"),
    imageAlt: "Bedroom in the Warmwood Studio",
    ...propertyPhotos("property-08", ["WhatsApp Image 2026-09-17 at 11.06.50.jpeg", "WhatsApp Image 2026-09-17 at 11.06.50 (1).jpeg", "WhatsApp Image 2026-09-17 at 11.06.50 (2).jpeg"], ["Studio bedroom", "Bed detail", "Window-side room"]),
    shortDescription: "A simple, sunny studio with a timber bedframe, fan, workspace, and room to settle in.",
    description: "A compact studio with the small details in place for an uncomplicated stay: a comfortable bed, daylight, and a useful desk.",
    bedrooms: "1 bedroom",
    beds: "1 bed",
    bathrooms: "1 bathroom",
    amenities: ["Air conditioning", "Wi-Fi", "Workspace", "Private bathroom"],
    houseRules: standardRules,
    rooms: [{ name: "Studio room", image: propertyPhoto("property-08", "WhatsApp Image 2026-09-17 at 11.06.50.jpeg") }],
  },
  {
    id: "property-009",
    name: "Slate City Suite",
    slug: "slate-city-suite",
    location: "Kuala Lumpur, Malaysia",
    area: "Bangsar",
    propertyType: "Entire apartment",
    collection: "City stays",
    guests: "Up to 3 guests",
    maxGuests: 3,
    price: "From RM 420 / night",
    priceValue: 420,
    currency: "MYR",
    heroImage: propertyPhoto("property-09", "Q2.jpeg"),
    imageAlt: "Living room in the Slate City Suite",
    ...propertyPhotos("property-09", ["Q1.jpeg", "Q2.jpeg", "Q3.jpeg", "Q4.jpeg"], ["Kitchen", "Living room", "Bathroom", "Bedroom"]),
    shortDescription: "A quietly dramatic city suite with dark finishes, an intimate lounge, and a refined bathroom.",
    description: "For guests who prefer an atmospheric, modern setting, this suite layers charcoal finishes with warm lighting and a self-contained layout.",
    bedrooms: "1 bedroom",
    beds: "1 bed",
    bathrooms: "1 bathroom",
    amenities: standardAmenities,
    houseRules: standardRules,
    rooms: [{ name: "Living room", image: propertyPhoto("property-09", "Q2.jpeg") }, { name: "Bedroom", image: propertyPhoto("property-09", "Q4.jpeg") }],
  },
  {
    id: "property-010",
    name: "Rosewood Family Apartment",
    slug: "rosewood-family-apartment",
    location: "Malaysia",
    area: "Mont Kiara",
    propertyType: "Entire apartment",
    collection: "City stays",
    guests: "Up to 5 guests",
    maxGuests: 5,
    price: "From RM 360 / night",
    priceValue: 360,
    currency: "MYR",
    heroImage: propertyPhoto("property-10", "K3.jpeg"),
    imageAlt: "Bedroom in the Rosewood Family Apartment",
    ...propertyPhotos("property-10", ["K1.jpeg", "K2.jpeg", "K3.jpeg", "K4.jpeg", "K5.jpeg", "K6.jpeg", "K7.jpeg", "K8.jpeg"], ["Kitchen", "Hallway", "Primary bedroom", "Second bedroom", "Living area", "Bedroom detail", "Bathroom", "Dining room"]),
    shortDescription: "A light, easy-going apartment with warm rose tones, a kitchen, and two restful bedrooms.",
    description: "The layout gives families room to separate and regroup, with comfortable bedrooms, a working kitchen, and a relaxed shared living space.",
    bedrooms: "2 bedrooms",
    beds: "3 beds",
    bathrooms: "1 bathroom",
    amenities: [...standardAmenities, "Family living area"],
    houseRules: standardRules,
    rooms: [{ name: "Primary bedroom", image: propertyPhoto("property-10", "K3.jpeg") }, { name: "Second bedroom", image: propertyPhoto("property-10", "K4.jpeg") }],
  },
  {
    id: "property-011",
    name: "Garden Light Residence",
    slug: "garden-light-residence",
    location: "Malaysia",
    area: "Shah Alam",
    propertyType: "Entire home",
    collection: "Homes",
    guests: "Up to 6 guests",
    maxGuests: 6,
    price: "From RM 720 / night",
    priceValue: 720,
    currency: "MYR",
    heroImage: propertyPhoto("property-11", "W2.jpeg"),
    imageAlt: "Garden-facing living room at Garden Light Residence",
    ...propertyPhotos("property-11", ["W1.jpeg", "W2.jpeg", "W3.jpeg", "W4.jpeg", "W5.jpeg", "W6.jpeg", "W7.jpeg", "W8.jpeg"], ["Open kitchen", "Garden lounge", "Bedroom", "Living and dining", "Bathroom", "Second bedroom", "Dining detail", "Outdoor view"]),
    shortDescription: "A refined garden-facing residence with an open kitchen, generous lounge, and soft natural light.",
    description: "A spacious home for unhurried days, with a sociable living room, well-finished kitchen, and quiet bedrooms connected to greenery outside.",
    bedrooms: "3 bedrooms",
    beds: "4 beds",
    bathrooms: "2 bathrooms",
    amenities: [...standardAmenities, "Garden outlook", "Dining area"],
    houseRules: standardRules,
    rooms: [{ name: "Garden lounge", image: propertyPhoto("property-11", "W2.jpeg") }, { name: "Bedroom", image: propertyPhoto("property-11", "W3.jpeg") }],
  },
  {
    id: "property-012",
    name: "Parkside Contemporary Home",
    slug: "parkside-contemporary-home",
    location: "Malaysia",
    area: "Subang Jaya",
    propertyType: "Entire home",
    collection: "Homes",
    guests: "Up to 4 guests",
    maxGuests: 4,
    price: "From RM 640 / night",
    priceValue: 640,
    currency: "MYR",
    heroImage: propertyPhoto("property-12", "A4.jpeg"),
    imageAlt: "Living room at Parkside Contemporary Home",
    ...propertyPhotos("property-12", ["A1.jpeg", "A2.jpeg", "A3.jpeg", "A4.jpeg"], ["Bedroom", "Kitchen", "Second bedroom", "Living room"]),
    shortDescription: "A polished home with layered textures, a beautiful kitchen, and leafy views through wide glass doors.",
    description: "A carefully designed stay for guests who enjoy strong material detail, calm bedrooms, and a living room that opens toward the green outside.",
    bedrooms: "2 bedrooms",
    beds: "2 beds",
    bathrooms: "2 bathrooms",
    amenities: [...standardAmenities, "Washer", "Garden outlook"],
    houseRules: standardRules,
    rooms: [{ name: "Bedroom", image: propertyPhoto("property-12", "A1.jpeg") }, { name: "Living room", image: propertyPhoto("property-12", "A4.jpeg") }],
  },
  {
    id: "property-013",
    name: "Maluri Transit Studio",
    slug: "maluri-transit-studio",
    location: "Maluri, Kuala Lumpur",
    area: "Maluri",
    propertyType: "Entire studio",
    collection: "City stays",
    guests: "Up to 2 guests",
    maxGuests: 2,
    price: "From RM 240 / night",
    priceValue: 240,
    currency: "MYR",
    heroImage: propertyPhoto("property-13", "Z2.jpeg"),
    imageAlt: "Studio bedroom at Maluri Transit Studio",
    ...propertyPhotos("property-13", ["Z1.jpeg", "Z2.jpeg", "Z3.jpeg", "Z4.jpeg", "Z5.jpeg", "Z6.jpeg", "Z7.jpeg", "Z8.jpeg", "Z9.jpeg", "Z10.jpeg"], ["Exterior", "Studio bedroom", "Second bedroom", "Lobby", "Kitchen", "Bathroom", "Workspace", "View", "Dining detail", "Building entrance"]),
    shortDescription: "A practical studio close to MRT Maluri, with a quiet sleeping area, workspace, and building amenities.",
    description: "Built for efficient city stays, this compact studio keeps the essentials close: a comfortable bed, workspace, kitchen facilities, and straightforward transport access.",
    bedrooms: "1 bedroom",
    beds: "1 bed",
    bathrooms: "1 bathroom",
    amenities: ["Air conditioning", "Wi-Fi", "Workspace", "Kitchenette", "Private bathroom"],
    houseRules: standardRules,
    rooms: [{ name: "Studio room", image: propertyPhoto("property-13", "Z2.jpeg") }],
  },
  {
    id: "property-014",
    name: "Bright Family Flat",
    slug: "bright-family-flat",
    location: "Malaysia",
    area: "Ampang",
    propertyType: "Entire apartment",
    collection: "Homes",
    guests: "Up to 5 guests",
    maxGuests: 5,
    price: "From RM 390 / night",
    priceValue: 390,
    currency: "MYR",
    heroImage: propertyPhoto("property-14", "E1.jpeg"),
    imageAlt: "Living and dining room at Bright Family Flat",
    ...propertyPhotos("property-14", ["E1.jpeg", "E2.jpeg", "E3.jpeg", "E4.jpeg", "E5.jpeg", "E6.jpeg", "E7.jpeg", "E8.jpeg", "E9.jpeg", "E10.jpeg"], ["Living and dining", "Kitchen", "Bathroom", "Living room", "Bedroom", "Second bedroom", "Balcony", "Exterior", "Building pool", "Parking"]),
    shortDescription: "A cheerful family apartment with a dining space, full kitchen, clean bathroom, and room to gather.",
    description: "A bright, uncomplicated home base where everyone can spread out, make breakfast, and return to a comfortable living room after a day out.",
    bedrooms: "2 bedrooms",
    beds: "3 beds",
    bathrooms: "1 bathroom",
    amenities: [...standardAmenities, "Dining area", "Family living area"],
    houseRules: standardRules,
    rooms: [{ name: "Living and dining", image: propertyPhoto("property-14", "E1.jpeg") }, { name: "Bedroom", image: propertyPhoto("property-14", "E5.jpeg") }],
  },
  {
    id: "property-015",
    name: "Quiet One-Bedroom Retreat",
    slug: "quiet-one-bedroom-retreat",
    location: "Malaysia",
    area: "Damansara",
    propertyType: "Entire apartment",
    collection: "City stays",
    guests: "Up to 3 guests",
    maxGuests: 3,
    price: "From RM 300 / night",
    priceValue: 300,
    currency: "MYR",
    heroImage: propertyPhoto("property-15", "R1.jpeg"),
    imageAlt: "Bedroom in the Quiet One-Bedroom Retreat",
    ...propertyPhotos("property-15", ["R1.jpeg", "R2.jpeg", "R3.jpeg", "R4.jpeg", "R5.jpeg", "R6.jpeg", "R7.jpeg", "R8.jpeg"], ["Bedroom", "Media wall", "Bedroom detail", "Kitchen", "Living area", "Bathroom", "Dining room", "View"]),
    shortDescription: "A calm one-bedroom apartment with a warm media wall, full kitchen, and space to take things slowly.",
    description: "A soft, lived-in apartment with a private bedroom and an easy shared space, suited to a short break or a longer work stay.",
    bedrooms: "1 bedroom",
    beds: "2 beds",
    bathrooms: "1 bathroom",
    amenities: standardAmenities,
    houseRules: standardRules,
    rooms: [{ name: "Bedroom", image: propertyPhoto("property-15", "R1.jpeg") }, { name: "Living area", image: propertyPhoto("property-15", "R5.jpeg") }],
  },
  {
    id: "property-016",
    name: "Softline City Residence",
    slug: "softline-city-residence",
    location: "Kuala Lumpur, Malaysia",
    area: "KL Sentral",
    propertyType: "Entire apartment",
    collection: "Homes",
    guests: "Up to 4 guests",
    maxGuests: 4,
    price: "From RM 580 / night",
    priceValue: 580,
    currency: "MYR",
    heroImage: propertyPhoto("property-16", "S1.jpeg"),
    imageAlt: "Bedroom in the Softline City Residence",
    ...propertyPhotos("property-16", ["S1.jpeg", "S2.jpeg", "S3.jpeg", "S4.jpeg", "S5.jpeg", "S6.jpeg", "S7.jpeg", "S8.jpeg", "S9.jpeg", "S10.jpeg"], ["Primary bedroom", "Bedroom detail", "Kitchen", "Bathroom", "Living room", "Dining area", "Second bedroom", "View", "Building amenities", "Entry"]),
    shortDescription: "A softly finished city residence with a serene bedroom, sculpted kitchen, and a spa-like bathroom.",
    description: "For guests drawn to quieter luxury, this residence pairs a restful palette with fine finishes and a complete apartment layout.",
    bedrooms: "2 bedrooms",
    beds: "2 beds",
    bathrooms: "2 bathrooms",
    amenities: [...standardAmenities, "Washer", "Dining area"],
    houseRules: standardRules,
    rooms: [{ name: "Primary bedroom", image: propertyPhoto("property-16", "S1.jpeg") }, { name: "Kitchen", image: propertyPhoto("property-16", "S3.jpeg") }],
  },
  {
    id: "property-017",
    name: "Sky-View Apartment",
    slug: "sky-view-apartment",
    location: "Kuala Lumpur, Malaysia",
    area: "Pudu",
    propertyType: "Entire apartment",
    collection: "City stays",
    guests: "Up to 3 guests",
    maxGuests: 3,
    price: "From RM 450 / night",
    priceValue: 450,
    currency: "MYR",
    heroImage: propertyPhoto("property-17", "D1.jpeg"),
    imageAlt: "Bedroom with city-facing windows at Sky-View Apartment",
    ...propertyPhotos("property-17", ["D1.jpeg", "D2.jpeg", "D3.jpeg", "D4.jpeg", "D5.jpeg", "D6.jpeg", "D7.jpeg", "D9.jpeg"], ["Bedroom view", "Second bedroom", "Bathroom", "Bedroom detail", "Kitchen", "Living room", "View", "Building exterior"]),
    shortDescription: "A streamlined high-rise apartment with floor-to-ceiling views, quiet bedrooms, and a crisp modern bath.",
    description: "Wide city-facing windows set the tone here, with a private bedroom, practical apartment layout, and a calm view to return to.",
    bedrooms: "2 bedrooms",
    beds: "2 beds",
    bathrooms: "1 bathroom",
    amenities: standardAmenities,
    houseRules: standardRules,
    rooms: [{ name: "Bedroom view", image: propertyPhoto("property-17", "D1.jpeg") }, { name: "Second bedroom", image: propertyPhoto("property-17", "D2.jpeg") }],
  },
  {
    id: "property-018",
    name: "The Gallery Residence",
    slug: "the-gallery-residence",
    location: "Kuala Lumpur, Malaysia",
    area: "Bukit Jalil",
    propertyType: "Entire apartment",
    collection: "Signature stays",
    guests: "Up to 4 guests",
    maxGuests: 4,
    price: "From RM 850 / night",
    priceValue: 850,
    currency: "MYR",
    heroImage: propertyPhoto("property-18", "X2.jpeg"),
    imageAlt: "Designer living room at The Gallery Residence",
    ...propertyPhotos("property-18", ["X1.jpeg", "X2.jpeg", "X3.jpeg", "X4.jpeg", "X5.jpeg", "X6.jpeg", "X7.jpeg", "X8.jpeg", "X9.jpeg", "X10.jpeg"], ["Bedroom", "Living room", "Dressing room", "Kitchen", "Dining area", "Bathroom", "Bedroom detail", "City view", "Building lounge", "Entry"]),
    shortDescription: "A cinematic design residence with a sculptural living room, rich bedroom, and gallery-like detailing.",
    description: "The most expressive stay in the collection, this residence layers warm timber, stone, tailored storage, and a lounge designed for lingering.",
    bedrooms: "2 bedrooms",
    beds: "2 beds",
    bathrooms: "2 bathrooms",
    amenities: [...standardAmenities, "Washer", "Dining area", "City view"],
    houseRules: standardRules,
    rooms: [{ name: "Living room", image: propertyPhoto("property-18", "X2.jpeg") }, { name: "Bedroom", image: propertyPhoto("property-18", "X1.jpeg") }],
  },
];

export const properties: Property[] = [...baseProperties, ...galleryProperties];

export const reviews: Array<{
  id: string;
  propertySlug: string;
  name: string;
  location: string;
  text: string;
}> = [];

export const demoBookings = [
  {
    id: "BK-1042",
    propertyName: "Patricia Modern Terrace Homestay",
    propertySlug: "patricia-modern-terrace-homestay",
    guestName: "Sarah Lim",
    email: "sarah@example.com",
    phone: "+60 12-222 8899",
    dates: "18 Oct - 21 Oct 2026",
    guests: "6 guests",
    status: "PENDING" as BookingStatus,
    price: "RM 1,860",
    request: "Family stay with an evening arrival.",
  },
  {
    id: "BK-1038",
    propertyName: "Patricia Modern Terrace Homestay",
    propertySlug: "patricia-modern-terrace-homestay",
    guestName: "Mark Tan",
    email: "mark@example.com",
    phone: "+60 17-456 1122",
    dates: "02 Nov - 05 Nov 2026",
    guests: "4 guests",
    status: "CONFIRMED" as BookingStatus,
    price: "RM 1,860",
    request: "Short residential stay for relatives visiting Selangor.",
  },
  {
    id: "BK-1029",
    propertyName: "Patricia Modern Terrace Homestay",
    propertySlug: "patricia-modern-terrace-homestay",
    guestName: "Aisha Rahman",
    email: "aisha@example.com",
    phone: "+60 19-888 4210",
    dates: "14 Sep - 17 Sep 2026",
    guests: "8 guests",
    status: "CANCELLED" as BookingStatus,
    price: "RM 1,860",
    request: "Family weekend gathering.",
  },
];

export const propertyTypes = ["Private terrace home"];
export const amenityOptions = ["Air conditioning", "Wi-Fi", "Kitchen", "Dining area", "Balcony", "Private bedrooms"];
